### ISSUE TITLE
Add container for dev branch

### ISSUE THREAD

**Issue by chelming** [petr-prikryl/OPDS-ABS#19]
Thanks for adding the workflow for the container registry! Could you add a dev tag for pushes to the dev branch?

**Comment by chelming** [comment]
maybe something like

```
name: Docker Image CI

on:
  push:
    branches: [ "*", "!master" ]
  pull_request:
    branches: [ "*", "!master" ]

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/opds-abs:${{ env.BRANCH }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/opds-abs:${{ env.BRANCH }}
```
