### ISSUE TITLE
Update documentation?

### ISSUE THREAD

**Issue by gundestrup** [petr-prikryl/OPDS-ABS#33]
Great plugin

I have been struggling with getting the docker to run on my synology nas, with the suggested config yaml file

I suggest the update to the documentation to be this
I have added network_mode and the ability to get the image directly, without having tot download it via git through commandline.

version: '4.0'
services:
  opds:
    image: ghcr.io/petr-prikryl/opds-abs:latest
    network_mode: 'host'
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # User/Group settings
      - PUID=1000  # Set to your user's UID for proper file permissions
      - PGID=1000  # Set to your user's GID for proper file permissions
      # Application settings
      - AUDIOBOOKSHELF_URL=http://<incert your host name here>:13378
      - AUTH_ENABLED=true
      - OPDS_LOG_LEVEL=DEBUG
      - CACHE_PERSISTENCE_ENABLED=true
      - ITEMS_PER_PAGE=25  # Set to 0 to show all items without pagination
    volumes:
      - <Incert you path to your local docker config here>:/app/opds_abs/data

Also I suggest that you also create a note regarding authentication.
So when people get the "pop up", that they should use ABS username / password
and not username + api authentication from abs.

regards
Svend

**Comment by chelming** [comment]
`the ability to get the image directly, without having tot download it via git through commandline.`

what do you mean by this? the sample compose file _does_ pull the image directly: https://github.com/petr-prikryl/OPDS-ABS/blob/master/docker-compose.yml

Why are you using host network mode? Is that something specific to Synology?

I disagree with the use of host mode on a general level and don't think it should be used for **any** container or image.

If you have a container that uses discovery through something like ssdp or mdns (home assistant, esphome, unifi), create a macvlan network and assign an IP address to the specific container.

Are there exceptions to my hatred for host mode? Maybe. But I haven't found one yet in the 50+ containers I'm running.


```yaml
networks:
  traefik_proxy:
    external: true
    name: traefik_proxy
  default:
    driver: bridge
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.10.0/24
```

```yaml
services:
  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    depends_on:
      - unifi-db
    env_file:
      - ${SECRETS}/.env.unifi
    volumes:
      - ${DOCKER_APPDATA}/unifi/config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional - controller discoverable on L2
      - 6789:6789 #optional - mobile throughput
    restart: unless-stopped
    networks:
      traefik_proxy: {}
      macvlan:
        ipv4_address: 192.168.10.202
        mac_address: 02:42:c0:a8:0a:02
```
